quarkus.temporal.connection.target=localhost:7233
%dev.quarkus.temporal.enable-mock=false
%dev.quarkus.compose.devservices.enabled=true
%dev.quarkus.compose.devservices.files=compose-devservices.yml
%test.quarkus.temporal.enable-mock=true
