quarkus.temporal.connection.target=localhost:7233
%dev.quarkus.temporal.enable-mock=false
%dev.quarkus.compose.devservices.enabled=true
%dev.quarkus.compose.devservices.files=compose-devservices.yml
%test.quarkus.temporal.enable-mock=true
%test.quarkus.compose.devservices.enabled=false
%dev.app.crypto.key-base64=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
%test.app.crypto.key-base64=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
